### ISSUE TITLE
Social images for Report tool not getting picked up in tweets/facebook

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#74]
We added a specific image for twitter to use for the newest report. It's not getting picked up with the tweet. Also, when we attach a facebook image the field won't populate on the backend. (suspect that it is not getting picked up in a facebook share either)

**Comment by sethrubenstein** [comment]
I'm seeing the image render in Facebook for the latest report...
![screenshot 2015-12-11 10 50 30](https://cloud.githubusercontent.com/assets/180264/11748175/06f944b2-9ff5-11e5-98f2-06ffdb85bb3f.png)

However on Twitter I see that there may be a probelm there - its trying to load the full image which is just too large for it so I'll need to set it so that the image Twitter tries to grab is much smaller.

**Comment by devansart** [comment]
Good to know that it gets picked up in Facebook. Any reason why I can't get the field to populate in that situation? Or could it be that the image you see is in facebook is the featured image assigned on the editor page?

Do you need me to assist in any way to get the twiiter image to work or is that you just have to point it to another crop that wordpress automatically generates?

**Comment by sethrubenstein** [comment]
The image for social always defaults to the featured image. There are however social overrides in the SEO field box. Yes for the twitter thing I just need to create a filter that says use the medium image size instead of full. Expect a release in an hour or so with that in place.

**Comment by sethrubenstein** [comment]
Okay we have a fix ready, will release as soon as possible.
